config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  #CSVのインポート
  post '/import_csv', to: 'users#import_csv'
  #出勤社員一覧
  get  '/attendance_users',    to: 'users#attendance_users'
  resources :account_activations, only: [:edit]
  resources :attendances
  
  #上長画面一ヶ月分勤怠申請のお知らせフォーム
  get  '/monthly_confirmation_form',    to: 'attendances#monthly_confirmation_form'
  post  '/monthly_confirmation_form',    to: 'attendances#monthly_confirmation_form'
  
  #一ヶ月分の申請
  patch  '/monthly_confirmation',    to: 'attendances#monthly_confirmation'
  #基本情報
  resources :basic_information
  #拠点情報
  resources :working_places
  #勤怠修正ログ
  resources :attendance_logs

  
  # 出勤画面表示・編集
  get  '/attendance_update', to: 'attendances#attendance_update'
  post '/attendance_update', to: 'attendances#attendance_update'
  patch '/attendance_update', to: 'attendances#attendance_update'


  get  '/attendance_edit', to: 'attendances#attendance_edit'
  post '/attendance_edit', to: 'attendances#attendance_edit'
  patch '/attendance_edit', to: 'attendances#attendance_edit'
  
  post  '/attendance_update_all', to: 'attendances#attendance_update_all'
  get   '/attendance_update_all', to: 'attendances#attendance_update_all'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :user_working_places, dependent: :destroy
  has_many :working_places, through: :user_working_places
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

 # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

   # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
    # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

 # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
    # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # クラスメソッド
  scope :attendancing, -> {
    joins(:attendances)
      .where('attendances.attendance_date = ?', Time.now.localtime('+09:00').to_date)
      .where('attendances.arriving_at < ?', DateTime.current)
      .where('attendances.leaving_at is null')
  }
  
  #CSVインポート
  def self.csv_attributes
    ["name", "email", "role", "employee_number", "card_id", "base_attendance_time", "start_attendance_time","end_attendance_time", "admin","password"]
  end
  
  def self.import_csv(file)
    CSV.foreach(file.path, headers:true) do |row|
      user = new
      user.attributes = row.to_hash.slice(*csv_attributes)
      user.save!
    end
  end
  
  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
   before_action :correct_user,   only: [:edit, :update]
   before_action :admin_user,     only: :destroy
   
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Emailを確認してアカウントの有効化をクリックしてください。"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを変更しました。"
      redirect_to @user
      # 更新に成功した場合を扱う。
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to users_url
  end
  
  def import_csv
    User.import_csv(params[:file])
    redirect_to users_url, notice: "ユーザーを追加しました"
  end
  
  # def users_csv(file)
  #   # User.rbに記述すべきだが、今回はusersをインポートするだけなのでusers_csvとしている。
  #   # usersを追加するだけなので、コントローラー内のメソッドに処理を記述する。
  #   CSV.foreach(file.path, headers: true) do |row|
  #     @User = User.new
  #     @User.attributes = row.to_hash.slice(*csv_attributes)
  #     @user.save!
  #   end
  # end
  
  def attendance_users
    @users = User.attendancing
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,:role, :employee_number, :card_id,
                                   :base_attendance_time, :start_attendance_time, :end_attendance_time, :password_confirmation)
    end
 # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
       store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      #アドミンユーザーなら編集できる
      if current_user.admin == true || current_user?(@user)
      else 
        redirect_to(root_url) 
      end
    end
    
     # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  #勤怠基本情報を指定のフォーマットで返します。 
  def time_format(time)  #format_basic_info(time) 
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_users_accordion.html.erb
<div class="container">
  <div id="accordion" class="panel-group">
  <% @users.each do |user| %>
    <li>
    <%= link_to user.name, user %>
    </li>
     <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除しますか？" }, :style=>"color:white;", class: "btn btn-sm btn-primary" %>
    <% end %>
    
      <!--繰り返す-->
      <div class="panel">
        <div class="panel-heading">
          <h4 class="panel-title">
          <!--idとして一意に特定できるようにする-->
            <a href="#<%= user.id %>" class="accordion-toggle collapsed btn btn-primary" data-toggle="collapse" data-parent="#accordion" style="color:white;">編集</a>
          </h4>
        </div>
        <!--idは一意に特定できるようにする-->
        <div id="<%= user.id %>" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
              <%= form_for user do |f| %>
              <%#= render 'shared/error_messages' %>
              <%= f.label :名前 %>
              <%= f.text_field :name, class: 'form-control' %>
            
              <%= f.label :メールアドレス %>
              <%= f.email_field :email, class: 'form-control' %>
                  
              <%= f.label :所属 %>
              <%= f.text_field :role, class: 'form-control' %>
                  
              <%= f.label :社員番号 %>
              <%= f.text_field :employee_number, class: 'form-control' %>
                  
              <%= f.label :カードID %>
              <%= f.text_field :card_id, class: 'form-control' %>
            
              <%= f.label :パスワード %>
              <%= f.password_field :password, class: 'form-control' %>
            
              <%= f.label :password_confirmation, "パスワード確認" %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
                  
              <%= f.label :指定勤務開始時間 %>
              <%= f.time_field :start_attendance_time, class: 'form-control' %>
                  
              <%= f.label :指定勤務終了時間 %>
              <%= f.time_field :end_attendance_time, class: 'form-control' %>
            
              <%= f.label :基本勤務時間 %>
              <%= f.time_field :base_attendance_time, class: 'form-control' %>
            
              <%= f.submit "プロフィールの変更", class: "btn btn-primary" %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/attendance_users.html.erb
<h1>出勤社員一覧</h1>
<div>
  <table class="table table-bordered table-striped table-condensed">
    <tr>
      <td class="table-body">社員番号</td>
      <td class="table-body">名前</td>
    </tr>  
    <% @users.each do |user| %>
    <tr>
      <td class="table-body"><%= link_to(user.employee_number) %></td>
      <td class="table-body"><%= link_to(user.name) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h2>名前、メールアドレス、所属、パスワード、指定勤務時間、基本勤務時間をご入力のうえ、【プロフィールの変更】をしてください。</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :所属 %>
      <%= f.text_field :role, class: 'form-control' %>
      
      <%= f.label :社員番号 %>
      <%= f.text_field :employee_number, class: 'form-control' %>
      
      <%= f.label :カードID %>
      <%= f.text_field :card_id, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :指定勤務開始時間 %>
      <%= f.time_field :start_attendance_time, class: 'form-control' %>
      
      <%= f.label :指定勤務終了時間 %>
      <%= f.time_field :end_attendance_time, class: 'form-control' %>

      <%= f.label :基本勤務時間 %>
      <%= f.time_field :base_attendance_time, class: 'form-control' %>

      <%= f.submit "プロフィールの変更", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">写真のアップロード</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザ一覧</h1>

<div class="import">
<%= form_tag(import_csv_path, :method => :post, multipart: true, class: "col-lg-4" ) do %>
  <%= file_field_tag(:file) %>
  <%= submit_tag "CSVインポート", class: "btn btn-primary btn-sm" %>
<% end %>
</div>
<br><br><br><br>
<div class="export">
  <%= link_to "ユーザ一覧のCSVエクスポート", users_path(format: :csv), class: "btn btn-primary btn-sm" %>
</div>
<br><br>
<%= will_paginate %>
<ul class="users">
    <%= render :partial => "users/users_accordion", :locals => { users: @users } %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h2>名前、メールアドレス、所属、パスワード、指定勤務時間、基本勤務時間をご入力のうえ、【新規ユーザーの追加】をしてください。</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :所属 %>
      <%= f.text_field :role, class: 'form-control' %>
      
      <%= f.label :社員番号 %>
      <%= f.text_field :employee_number, class: 'form-control' %>
      
      <%= f.label :カードID %>
      <%= f.text_field :card_id, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :パスワード確認 %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :指定勤務開始時間 %>
      <%= f.time_field :start_attendance_time, class: 'form-control' %>
      
      <%= f.label :指定勤務終了時間 %>
      <%= f.time_field :end_attendance_time, class: 'form-control' %>

      <%= f.label :基本勤務時間 %>
      <%= f.time_field :base_attendance_time, class: 'form-control' %>
      
      <%= f.submit "新規ユーザーの追加", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <ul>
        <%= link_to "勤怠の登録をする", attendances_path, class: "nav-link" %> 
      </ul>
    </section>
  </aside>
</div>

<table class="table">
    <thead>
      <!-- セルに背景色を変更 -->
        <tr class="active">
            <th>名前</th>
            <th>メールアドレス</th>
            <th>所属</th>
            <th>社員番号</th>
        </tr>
    </thead>
    <tbody>
        <!-- 行全体をブルーに -->
        <tr class="info">
            <td><%= @user.name %></td>
            <td><%= @user.email %></td>
            <td><%= @user.role %></td>
            <td><%= @user.employee_number %></td>
        </tr>
　　　<thead>
        <tr class="active">
            <th>カードID</th>
            <th>指定勤務開始時間</th>
            <th>指定勤務終了時間</th>
            <th>基本勤務時間</th>
        </tr>
    </thead>
        <tr>
            <!-- セルに背景色を変更 -->
            <td class="info"><%= @user.card_id %></td>
            <td class="info"><%= time_format(@user.start_attendance_time)%></td>
            <td class="info"><%= time_format(@user.end_attendance_time) %></td>
            <td class="info"><%= time_format(@user.base_attendance_time) %></td>
        </tr>
    </tbody>
</table>