config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  #CSVのインポート
  post '/import_csv', to: 'users#import_csv'
  #出勤社員一覧
  get  '/attendance_users',    to: 'users#attendance_users'
  resources :account_activations, only: [:edit]
  resources :attendances
  
  #上長画面一ヶ月分勤怠申請のお知らせフォーム
  get  '/monthly_confirmation_form',    to: 'attendances#monthly_confirmation_form'
  post  '/monthly_confirmation_form',    to: 'attendances#monthly_confirmation_form'
  
  #一ヶ月分の申請
  patch  '/monthly_confirmation',    to: 'attendances#monthly_confirmation'
  #基本情報
  resources :basic_information
  #拠点情報
  resources :working_places
  #勤怠修正ログ
  resources :attendance_logs

  
  # 出勤画面表示・編集
  get  '/attendance_update', to: 'attendances#attendance_update'
  post '/attendance_update', to: 'attendances#attendance_update'
  patch '/attendance_update', to: 'attendances#attendance_update'


  get  '/attendance_edit', to: 'attendances#attendance_edit'
  post '/attendance_edit', to: 'attendances#attendance_edit'
  patch '/attendance_edit', to: 'attendances#attendance_edit'
  
  post  '/attendance_update_all', to: 'attendances#attendance_update_all'
  get   '/attendance_update_all', to: 'attendances#attendance_update_all'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  enum monthly_confirmation_status: { nothing: 0, pending: 1, approval: 2, denial: 3 }
  
  # 【所属長承認のお知らせ】一ヶ月支持者確認がログインユーザーで、ステータスが未承認かどうか＆何月分の勤怠
  def self.monthly_confirmation(current_user)
    attendances = self.where(monthly_confirmation_status: :pending, monthly_confirmation_approver_id: current_user.id)
    year_month_arr = []
    attendances.all.each do |attendance|
      year_month_arr << attendance.attendance_date.year.to_s + attendance.attendance_date.month.to_s
    end
    year_month_arr.uniq.count
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @user = current_user
    #指示者確認（印）上長の選択
    @seniors = User.where(is_senior: true).map(&:name)
    
    # 曜日表示用に使用する
    @youbi = %w[日 月 火 水 木 金 土]
    
    # 既に表示月があれば、表示月を取得する
    if !params[:first_day].nil?
      @first_day = Date.parse(params[:first_day])
    else
      # 表示月が無ければ、今月分を表示
      @first_day = Date.new(Date.today.year, Date.today.month, 1)
    end
    # 最終日を取得する
    @last_day = @first_day.end_of_month
    # 今月の初日から最終日の期間分を取得
    (@first_day..@last_day).each do |date|
      # 該当日付のデータがないなら作成する
      #(例)user1に対して、今月の初日から最終日の値を取得する
      if !@user.attendances.where('attendance_date = ?', date).present? #{|attendance| attendance.attendance_date == date }
        linked_attendance = Attendance.new(user_id: @user.id, attendance_date: date)
        linked_attendance.save
      end
    end
    # 表示期間の勤怠データを日付順にソートして取得 show.html.erb、 <% @attendances.each do |attendance| %>からの情報
    @attendances = @user.attendances.where('attendance_date >= ? and attendance_date <= ?', @first_day, @last_day).order("attendance_date ASC")
    
    # 上長画面で一ヶ月分勤怠申請のお知らせをカウントする
    @monthly_confirmation_count = Attendance.monthly_confirmation(current_user)
  end
  
  def new
  end
  
  def create
  end
  
  def show
  end
  
  def edit
    @attendance = Attendance.find(params[:id])
    @seniors = User.where(is_senior: true).map(&:name)
    @youbi = %w[日 月 火 水 木 金 土]
  end
  
  def update
    #todo
    @attendance = Attendance.find(params[:id])
    
    tmp_date = @attendance.attendance_date
    tmp_hour = params[:attendance][:overtime].split(":")[0].to_i
    tmp_min = params[:attendance][:overtime].split(":")[1].to_i
    @attendance.overtime = tmp_date + tmp_hour.hour + tmp_min.minute
    
    #チェックボックスはifで分岐だけでデータベースには入れない
    if params[:overday_check]
      @attendance.overtime = @attendance.overtime + 1.day
    end 
    
    @attendance.user_id = current_user.id
    #指示者確認・パラメーターでユーザーの名前を検索してidを入れる
    @attendance.overwork_approver_id = User.where(name: params[:user][:name]).first.id
    @attendance.task_memo = params[:attendance][:task_memo]
    if @attendance.save
      redirect_to attendances_path, notice: '残業申請を送付しました。' 
    else
      redirect_to attendances_path, notice: '残業申請は失敗しました。' 
    end
  end
  
  def destroy
  end
  
    #一ヶ月分の勤怠申請
  def monthly_confirmation
    @first_day = params[:year_month]
    #datetimeに変換
    @first_day = @first_day.to_datetime
    @last_day = @first_day.end_of_month
    #パラメーターでユーザーの名前を検索してidを入れる
    _id = User.where(name: params[:user][:name]).first.id
    #一ヶ月分の勤怠検索して上長IDとステータスの申請して保存する
    Attendance.where('attendance_date >= ? and attendance_date <= ?', @first_day-1.minute, @last_day).update_all(:monthly_confirmation_approver_id => _id, :monthly_confirmation_status => :pending)
  end
  
    #上長承認モーダル画面・ユーザーからの1ヶ月分勤怠
  def monthly_confirmation_form
    #未承認かつidがcurrent_user
    @attendances = Attendance.where(monthly_confirmation_status: :pending, monthly_confirmation_approver_id: current_user.id)
    #ユーザー（user_id)ごとに勤怠のオブジェクトを分ける
    tmp_pending_users = @attendances.group_by(&:user_id)
    #未承認のユーザーの名前と、何月分の一ヶ月勤怠申請なのか
    @pending_users = {}
    tmp_pending_users.each do |user_id, attendances|
      year_month_arr = []
      attendances.each do |attendance|
        year_month_arr << attendance.attendance_date.year.to_s + attendance.attendance_date.month.to_s
      end
      year_month_arr.uniq
      @pending_users.store(User.find(user_id).name, year_month_arr.uniq)
    end
  end
  
  # 出勤・退社ボタン押下　show.html.erbの出社・退社押下時反応
  def attendance_update
    # 更新する勤怠データを取得
    @attendance = Attendance.find(params[:attendance][:id])
    # 更新パラメータを文字列で取得する
    @update_type = params[:attendance][:update_type]

    if @update_type == 'arriving_at'
      # 出社時刻を更新 
      if !@attendance.update_column(:arriving_at, DateTime.new(DateTime.now.year, DateTime.now.month, DateTime.now.day,DateTime.now.hour,DateTime.now.min,0))
        flash[:error] = "出社時間の入力に失敗しました"
      end
    elsif @update_type == 'leaving_at'
      # 退社時刻を更新 
      if !@attendance.update_column(:leaving_at, DateTime.new(DateTime.now.year, DateTime.now.month, DateTime.now.day,DateTime.now.hour,DateTime.now.min,0))
        flash[:error] = "退社時間の入力に失敗しました"
      end
    end  
    #出社・退社押下した日付及び現在のuser idを@userに返す
    @user = User.find(params[:attendance][:user_id])
    redirect_to attendances_path
  end
  
  
  def attendance_edit
    @user = User.find(params[:id])
    #指示者確認（印）上長の選択
    @seniors = User.where(is_senior: true).map(&:name)

    # 曜日表示用に使用する
    @youbi = %w[日 月 火 水 木 金 土]
    
    # 既に表示月があれば、表示月を取得する
    if !params[:first_day].nil?
      @first_day = Date.parse(params[:first_day])
    else
      # 表示月が無ければ、今月分を表示
      @first_day = Date.new(Date.today.year, Date.today.month, 1)
    end
    #最終日を取得する
    @last_day = @first_day.end_of_month

    # 今月の初日から最終日の期間分を取得
    (@first_day..@last_day).each do |date|
      # 該当日付のデータがないなら作成する
      #(例)user1に対して、今月の初日から最終日の値を取得する
      if !@user.attendances.any? {|attendance| attendance.attendance_date == date }
        linked_attendance = Attendance.create(user_id: @user.id, day: date)
        linked_attendance.save
      end
      
    # 表示期間の勤怠データを日付順にソートして取得 show.html.erb、 <% @attendances.each do |attendance| %>からの情報
    @attendances = @user.attendances.where('attendance_date >= ? and attendance_date <= ?', @first_day, @last_day).order("attendance_date ASC")
    end
  end

  #編集ページ更新  
  def attendance_update_all
    @user = User.find_by(id: params[:id])
    error_count = 0
    message = ""
    
    attendances_params.each do |id, item|
      attendance = Attendance.find(id)
      
      #出社時間と退社時間の両方の存在を確認
      if item["arriving_at"].blank? && item["leaving_at"].blank?
        message = '一部編集が無効となった項目があります。'
        
      # 当日以降の編集はadminユーザのみ
      elsif attendance.attendance_date > Date.current && !current_user.admin?
        message = '明日以降の勤怠編集は出来ません。'
        error_count += 1
      
      #出社時間 > 退社時間ではないか
      elsif item["arriving_at"].to_s > item["leaving_at"].to_s
        message = '出社時間より退社時間が早い項目がありました'
        error_count += 1
      end
    end #eachの締め
    
    if error_count > 0
      flash[:warning] = message
    else
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        
        # 当日以降の編集はadminユーザのみ
        if item["arriving_at"].blank? && item["leaving_at"].blank?
        
        else
          if params["attendances"][id]["change_confirmation_approver_id"]
            item["change_confirmation_approver_id"] = User.where(name: params["attendances"][id]["change_confirmation_approver_id"]).first.id.to_i
            attendance.update_attributes(item)
            flash[:success] = '勤怠時間を更新しました。'
          else
            attendance.update_attributes(item)
            flash[:success] = '勤怠時間を更新しました。'
          end
        end
      end #eachの締め
    end
    redirect_to attendances_url(@user, params:{ id: @user.id, first_day: params[:first_day]})
  end
  
  private

  def attendances_params
    params.permit(attendances: [:arriving_at, :leaving_at, :note, :overwork_approver_id])[:attendances]
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def attendance_count
    Attendance.where(user_id: params[:id], attendance_date: Time.new(@first_day.year,@first_day.month).all_month).select("leaving_at").count
  end
  
  # 在社時間計上用
  def working_hours(a,b)
    arriving_at = Time.mktime(a.year, a.month, a.day, a.hour, a.min, 0, 0)
    leaving_at = Time.mktime(b.year, b.month, b.day, b.hour, b.min, 0, 0)
    #(((leaving_at - arriving_at) / 60) / 60).truncate()
    (Time.parse("1/1") + (leaving_at - arriving_at)).strftime("%H時間%M分")
  end
  
  # 引数の時刻データの秒を０にして差を求める
  def times(x,y)
    c = Time.mktime(x.year, x.month, x.day, x.hour, x.min, 0, 0)
    d = Time.mktime(y.year, y.month, y.day, y.hour, y.min, 0, 0)
    (d - c).to_i
  end
  
  # 基本時間などの時刻データを指定の１０段階表示にする
  def basic_info_time(t)
    format("%.2f", ((t.hour * 60.0) + t.min)/60) if !t.blank?
  end
end

app/views/attendances/_monthly_confirmation_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="monthly_confirmation_form">
    <%= @attendances.count %>
    <% @pending_users.each do |user_name, attendances| %>
    <h1><%= user_name %>からの１ヶ月分勤怠申請</h1>
    <%= user_name %>
    <%= attendances %>
    <% end %>
    
      <% if false %>
      <%= form_tag(@attendances, remote: true) do |f| %>
        <table class = "table-bordered table-striped table-condensed">
          <thead>
            <thead>
              <tr>
                <th width = "10%">月</th>
                <th width = "20%">指示者確認（印）</th>
                <th width = "10%">変更</th>
                <th width = "30%">勤怠を確認する</th>
              </tr>
            </thead>
          </thead>
          <tbody>
            <tr>
              <!--月-->
              <td class = "attendance_date"><%= f.object.attendance_date.month %>/<%= f.object.attendance_date.day %></td>
              <!--指示者確認（印)--> { nothing: 0, pending: 1, approval: 2, denial: 3 }
              <td><%= select :attendance, :name, @seniors, :prompt => "選択してください" %></td>
              <!--変更のチェックボックス、チェックがないと変更しても反映されない-->
            　<td><%= check_box_tag :overday_check %></td>
              <!--勤怠を確認するボタン-->
              <td><%= link_to "確認", edit_attendance_path(attendance), remote: true, :style=>"color:white;", class: "btn btn-sm btn-primary" %></td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "変更を送信する", class: "btn btn-primary btn-sm" %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_overwork_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <h1>残業申請</h1>
    <div class="overwork_form">
      <%= form_for(@attendance, remote: true) do |f| %>
        <table class = "table-bordered table-striped table-condensed">
          <thead>
            <thead>
              <tr>
                <th width = "10%">日付</th>
                <th width = "10%">曜日</th>
                <th width = "20%">終了予定時間</th>
                <th width = "10%">翌日</th>
                <th width = "30%">業務処理内容</th>
                <th width = "20%">指示者確認（印）</th>
              </tr>
            </thead>
          </thead>
          <tbody>
            <tr>
              <!--日付-->
              <td class = "attendance_date"><%= f.object.attendance_date.month %>/<%= f.object.attendance_date.day %></td>
              <!--曜日-->
              <td class = "attendance_date"><%= @youbi[f.object.attendance_date.wday] %></td>
              <!--終了予定時間-->
              <td><%= f.time_field :overtime %></td>
              <!--翌日のチェックボックス-->
            　<td><%= check_box_tag :overday_check %></td>
              <!--業務処理内容-->
              <td><%= f.text_field :task_memo %></td>
              <!--指示者確認（印)-->
              <td><%= select :user, :name, @seniors,  :prompt => "選択してください" %></td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "変更を送信する", class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/attendance_edit.html.erb
<% provide(:title,"勤怠編集画面" ) %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_for(@user, url: attendance_update_all_path, method: :post) do |f| %>
    <table class = "table-bordered table-striped table-condensed">
      <thead>
        <thead>
          <tr>
            <th width = "10%">日付</th>
            <th width = "5%">曜日</th>
            <th width = "15%">出社</th>
            <th width = "15%">退社</th>
            <th width = "5%">翌日</th>
            <th width = "10%">在社時間</th>
            <th width = "29%">備考</th>
            <th width = "18%">指示者確認（印）</th>
          </tr>
        </thead>
      </thead>
      <tbody>
      <%= hidden_field_tag :id, @user.id %>
      <%= hidden_field_tag :first_day, @first_day %>
      <% @attendances.each do |d| %>
      <%= fields_for "attendances[]", d do |tf| %>
        <tr>
          <!--日付-->
          <td class = "attendance_date"><%= d.attendance_date.to_s(:attendance_date) %></td>
          <!--曜日-->
          <td class = "attendance_date"><%= @youbi[d.attendance_date.wday] %></td>
          <!--出勤-->
          <td><%= tf.time_field :arriving_at, class: "form-control tf" %></td>
          <!--退勤-->
          <td><%= tf.time_field :leaving_at, class: "form-control tf" %></td>
          <!--翌日のチェックボックス-->
          <td><%= check_box_tag :overday_check %></td>
          <!--在社時間の秒計算-->
          <td><%= working_hours(d.arriving_at,d.leaving_at) if d.arriving_at.present? && d.leaving_at.present? %></td>
          <!--備考の入力フォーム-->
          <td><%= tf.text_field :note, :size=>"100", class: "form-control tf" %></td>
          <!--指示者確認（印）セレクトフォーム-->
          <td><%= tf.select :change_confirmation_approver_id, options_for_select(@seniors) %></td>
        </tr>
      <% end %>
      <% end %>
      </tbody>
    </table>
    <center>
    <%= f.submit "編集内容を更新", style:"width:300px", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "キャンセル", user_url(@user, params:{first_day: @first_day }), style:"width:300px", class: "btn btncancel btn-default" %>
    </center>
</div>

app/views/attendances/edit.js.erb
$("#overwork-form-modal").html("<%= escape_javascript(render 'overwork_form') %>")
$("#overwork-form-modal").modal("show")

app/views/attendances/index.html.erb
<% provide(:title, "勤怠システム") %>
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <div class = "header">  
      <tr>
        <th colspan="2" class="table-header" width="250">
          <%= link_to "◀︎", attendances_path(params: { id: @user.id, first_day: @first_day.prev_month }), style: "color:white", class: 'btn btn-primary btn-sm' %>  
          <%= @first_day.strftime("%Y年%m月") %>　時間管理表　
          <%= link_to "▶︎", attendances_path(params: { id: @user.id, first_day: @first_day.next_month }), style: "color:white", class: 'btn btn-primary btn-sm' %>
        </th>
        <th class="table-header">指定勤務開始時間　<%= time_format(@user.start_attendance_time) %></th>
        <th colspan="2" class="table-header">基本時間 <%= time_format(@user.base_attendance_time) %></th>
        <th class="table-header">初日  <%= @first_day.strftime("%m/%d") %></th>
        <th class="table-header">締め　<%= @last_day.strftime("%m/%d") %></th>
      </tr>
      <tr>
        <th class="table-header">所属 <%= @user.role %></th>
        <th class="table-header">社員番号 <%= @user.employee_number %></th>
        <th class="table-header">氏名　<%= @user.name %></th>
        <th class="table-header">カードID</th>
        <th class="table-header"><%= @user.card_id %></th>
        <th colspan="2" class="table-header">出勤日数　<%= attendance_count %>日</th>
      </tr>
    </div>  
  </thead>
</table>
<!--上長で（自分かどうか）&未承認だったら申請のお知らせの表示・未承認のものがあれば文字は赤色-->
<% if current_user.is_senior %>
<!-- 所属長承認リンクを押すとモーダルへ飛ぶ-->
<%= link_to "【所属長承認のお知らせ】", monthly_confirmation_form_path, remote: true %>
  <div id="monthly-confirmation-form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <!-- 所属長承認の件数をカウントする-->
  <%= @monthly_confirmation_count %>
<% end %>

<!--attendance_edit_pathに、userのidと今月の値を渡す-->
<div class="actions">
  <%= link_to "　　　勤怠を編集　　　", attendance_edit_url(@attendance, params: { id: @user.id, first_day: @first_day }), :style=>"color:white;", class: "btn btn-primary btn-sm" %>
  <%= link_to "　　　CSV出力　　　", attendances_path(format: :csv), class: "btn btn-primary btn-sm" %>
  <%= link_to "勤怠修正ログ（承認済）", attendance_logs_path(@attendance, params: { id: @user.id, first_day: @first_day }), :style=>"color:white;", class: "btn btn-primary btn-sm" %>
</div>

<table class="table table-bordered table-striped table-condensed">
  <thead>
    <tr>
      <th rowspan="3" class="table-header" width="90">残業申請</th>
      <th rowspan="3" class="table-header" width="50">日付</th>
      <th rowspan="3" class="table-header" width="50">曜日</th>
      <th colspan="8" class="table-header" width="180">実績</th>
      <th colspan="10" class="table-header" width="180">所定外勤務</th>
    </tr>
    
    <tr>   
     <th colspan="3" class="table-header" width="180">出社</th>
     <th colspan="3" class="table-header" width="180">退社</th>
     <th rowspan="2" class="table-header" width="100">在社時間</th>
     <th rowspan="2" class="table-header" width="70">備考</th>
     <th colspan="2" class="table-header" width="120">終了予定時間</th>
     <th rowspan="2" class="table-header" width="100">時間外時間</th>
     <th rowspan="2" class="table-header" width="100">業務処理内容</th>
     <th rowspan="2" class="table-header" width="130">指示者確認（印）</th>
    </tr>
    
    <tr>   
     <th class="table-header" width="50">時</th>
     <th class="table-header" width="50">分</th>
     <th class="table-header" width="50">  </th>
     <th class="table-header" width="50">時</th>
     <th class="table-header" width="50">分</th>
     <th class="table-header" width="50">  </th>
     <th class="table-header" width="50">時</th>
     <th class="table-header" width="50">分</th>
    </tr>
  </thead>
  <tbody>
  <!-- attendance_controller.rbの@attendancesの中身を見にいく-->
  <% total_present_time = 0 %>
  <% @attendances.each do |attendance| %>
  <%= form_for(attendance, url: attendance_update_path ) do |f| %>
  <%= f.hidden_field :user_id, :value => "#{@user.id}"%>
  <%= f.hidden_field :id, :value => "#{attendance.id}"%>
    <tr>
      <!-- 残業申請ボタンを押すとモーダルへ飛ぶ-->
      <td class="table-body"><%= link_to "残業申請", edit_attendance_path(attendance), remote: true, :style=>"color:white;", class: "btn btn-sm btn-primary" %>
        <div id="overwork-form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
          <!--日付-->
          <td class="table-body"><%= attendance.attendance_date.month %>/<%= attendance.attendance_date.day %></td>
          <!--曜日-->
          <td class="table-body"><%= @youbi[attendance.attendance_date.wday] %></td>
          <!-- 出社時間の表示  -->
          <td class="table-body">
            <%= attendance.arriving_at.hour if !attendance.arriving_at.nil? %>
          </td>
          <td class="table-body">
            <%= attendance.arriving_at.min if !attendance.arriving_at.nil? %>
          </td>
          <td class="table-body">
            <!-- 自身の勤怠で出社時間と退社時間が空なら表示  -->
            <% if current_user == @user && attendance.arriving_at.nil? && attendance.leaving_at.nil? && attendance.attendance_date == Date.today %>
            <%= f.hidden_field :update_type, :value => "arriving_at"%>
            <%= f.submit "出社", class: "btn btn-primary btn-block" %>
            <% end %>
          </td>
          <!-- 退社時間の表示  -->
          <td class="table-body">
            <%= attendance.leaving_at.hour if !attendance.leaving_at.nil? %>
          </td>
          <td class="table-body">
            <%= attendance.leaving_at.min if !attendance.leaving_at.nil? %>
          </td>
          <td class="table-body">
            <!-- 出社時間入力済みかつ退社時間が空なら表示  -->
            <% if current_user == @user && !attendance.arriving_at.nil? && attendance.leaving_at.nil? && attendance.attendance_date == Date.today %>
            <%= f.hidden_field :update_type, :value => "leaving_at"%>
            <%= f.submit "退社", class: "btn btn-primary btn-block" %>
            <% end %>
          </td>
          <!-- 在社時間の表示  -->
          <td class="table-body">
            <% if !attendance.arriving_at.nil? && !attendance.leaving_at.nil? %>
            <%= f.hidden_field :update_type, :value => "arriving_at"%>
            <%= f.hidden_field :update_type, :value => "leaving_at"%>
            <%= working_hours(attendance.arriving_at,attendance.leaving_at) if attendance.arriving_at.present? && attendance.leaving_at.present? %>
            <% end %>
          </td>
          <!-- 備考の表示  -->
          <td class="table-body"><%= attendance.note %>
          </td>
          <!-- 終了予定時間の表示  -->
          <td class="table-body"><%= attendance.overtime.try(:hour) %>
          </td>
          <!-- 終了予定時間の表示  -->
          <td class="table-body"><%= attendance.overtime.try(:min) %>
          </td>
          <!-- 時間外時間の表示  -->
          <td class="table-body">
          </td>
          <!-- 業務処理内容の表示  -->
          <td class="table-body"><%= attendance.task_memo %>
          </td>
          <!-- 指示者確認（印）の表示  -->
          <td class="table-body"><%= User.find(attendance.overwork_approver_id.to_i).name if attendance.overwork_approver_id %>
          </td>
        </tr>
      </div>
    </td>
  <% end %>
  <% end %>
    <tr>
      <td colspan="9" class="table-body"></td>
      <!-- 合計在社時間の表示 -->
      <td class="table-body">
        <%= format("%.2f", total_present_time) %>
      </td>
      <td colspan="5" class="table-body"></td>
      <td class="table-body">所属長承認
        <%= form_tag(monthly_confirmation_path, method: :patch) do %>
        <%= select :user, :name, @seniors, :prompt => "選択してください" %>
        <%= hidden_field_tag :year_month, @first_day %>
        <%= submit_tag("申請", class: "btn btn-primary btn-block btn-sm")%>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/attendances/monthly_confirmation_form.js.erb
$("#monthly-confirmation-form-modal").html("<%= escape_javascript(render 'monthly_confirmation_form') %>")
$("#monthly-confirmation-form-modal").modal("show")

app/views/attendances/new.js.erb
$("#overwork-form-modal").html("<%= escape_javascript(render 'overwork_form') %>")
$("#overwork-form-modal").modal("show")